analog_turbidity_controller = Analog turbidity controller
    .abbreviation = ATUC
    .hover = Analog turbidity controller
digital_disolved_oxygen_controller = Digital disolved oxygen controller
    .abbreviation = DDOC
    .hover = Digital disolved oxygen controller
digital_disolved_oxygen_controller_concentration_channel = Concentration channel { $index }
    .abbreviation = C{ $index }
    .hover = Digital disolved oxygen controller, concentration channel { $index }
digital_disolved_oxygen_controller_temperature_channel = Temperature channel { $index }
    .abbreviation = T{ $index }
    .hover = Digital disolved oxygen controller, temperature channel { $index }
digital_disolved_oxygen_controller_voltage_channel = Voltage channel { $index }
    .abbreviation = V{ $index }
    .hover = Digital disolved oxygen controller, voltage channel { $index }
digital_temperature_controller = Digital temperature controller
    .abbreviation = DTEC
    .hover = Digital temperature controller

in_real_time = In real time
loaded_files = Files
    .hover = Loaded files
delete_all = Delete all
